### ISSUE TITLE
Registration Feature  not working

### ISSUE THREAD

**Issue by nareshkumar-h** [csy-batch-2021/shopping-app-api#2]
#### Expected Behavior
* User should be registered successfully.

#### Current Behavior
* Throws error message.

#### Reference

![image](https://user-images.githubusercontent.com/2763774/107740031-2a45b000-6d30-11eb-8fe1-9a0d6368fa18.png)

**Comment by Dharaneeshwaran97** [comment]
Now it's  fixed in  database, can you please retest it.

**Comment by nareshkumar-h** [comment]
Thank you. I will retest now.

**Comment by nareshkumar-h** [comment]
## Retesting

* It is working as expected.
![image](https://user-images.githubusercontent.com/2763774/107740927-2c107300-6d32-11eb-9aba-370acb8eafd7.png)
